batch_size: 64

model: 
  _target_: bridge_matching.model.BridgeMatchingModel
  predict_type: x_orig

bridge:
  _target_: bridge_matching.bridge.BrownianBridge
  gamma: 0.1

sampling_params:
  num_steps: 50
  vis_steps: 10
  timesteps: diffusion
  rho: 10
  sigma_max: 1
  sigma_min: 1e-2

transform:
  _target_: bridge_matching.transform.InpaintingTransform


images_dir: datasets/ffhq/predict_images
checkpoint_path: checkpoints/2024.12.21-04.20.15_ffhq_inpainting_latest.ckpt

metrics:
  - _target_: bridge_matching.metric.FIDMetric
    name: FID
    ref_path: stats/ffhq
    num_expected: 10000
    batch_size: ${batch_size}

data:
  test:
    batch_size: ${batch_size}
    num_workers: 5
    datasets:
      - _target_: bridge_matching.dataset.FFHQDataset
        root_dir: datasets/ffhq/test

