task_name: ffhq_inpainting
batch_size: 32
resume: false

logging:
  debug: false
  project: bridge_matching
  #resume: False
  mode: online
  name: ${now:%Y.%m.%d-%H.%M.%S}_${task_name}
  tags: ["${task_name}"]
  id: null
  group: null

model: 
  _target_: bridge_matching.model.UNet

sampler:
  num_steps: 20
  vis_steps: 10
  gamma: 0.5

loss:
  _target_: bridge_matching.loss.BridgeMatchingLoss
  gamma: ${sampler.gamma}

transform:
  _target_: bridge_matching.transform.InpaintingTransform

# data:
#   train:
#     batch_size: ${batch_size}
#     num_workers: 5
#     datasets:
#       - _target_: bridge_matching.dataset.FFHQDataset
#         root_dir: datasets/ffhq/train
#   test:
#     batch_size: ${batch_size}
#     num_workers: 5
#     datasets:
#       - _target_: bridge_matching.dataset.FFHQDataset
#         root_dir: datasets/ffhq/test

data:
  train:
    batch_size: ${batch_size}
    num_workers: 5
    datasets:
      - _target_: bridge_matching.dataset.ColoredMNIST
        root: datasets/colored_mnist
        train: true
        download: true
  test:
    batch_size: ${batch_size}
    num_workers: 5
    datasets:
      - _target_: bridge_matching.dataset.ColoredMNIST
        root: datasets/colored_mnist
        train: false
        download: true

optimizer:
  _target_: torch.optim.Adam
  lr: 1e-4

lr_scheduler:
  _target_: torch.optim.lr_scheduler.ExponentialLR
  gamma: 1

trainer:
  log_step: 100
  len_epoch: 1000
  epochs: 30
  grad_norm_clip: 100
