task_name: ffhq_inpainting
batch_size: 32
resume: false

logging:
  debug: false
  project: bridge_matching
  #resume: False
  mode: online
  name: ${now:%Y.%m.%d-%H.%M.%S}_${task_name}
  tags: ["${task_name}"]
  id: null
  group: null

model: 
  _target_: bridge_matching.model.UNet

bridge:
  _target_: bridge_matching.bridge.BrownianBridge
  gamma: 0.01

sampling_params:
  num_steps: 50
  vis_steps: 10
  timesteps: uniform

# sampling_params:
#   num_steps: 20
#   vis_steps: 10
#   timesteps: diffusion
#   rho: 7
#   sigma_max: 1
#   sigma_min: 1e-4

loss:
  _target_: bridge_matching.loss.BridgeMatchingLoss

transform:
  _target_: bridge_matching.transform.InpaintingTransform

# data:
#   train:
#     batch_size: ${batch_size}
#     num_workers: 5
#     datasets:
#       - _target_: bridge_matching.dataset.FFHQDataset
#         root_dir: datasets/ffhq/train
#   test:
#     batch_size: ${batch_size}
#     num_workers: 5
#     datasets:
#       - _target_: bridge_matching.dataset.FFHQDataset
#         root_dir: datasets/ffhq/test

data:
  train:
    batch_size: ${batch_size}
    num_workers: 5
    datasets:
      - _target_: bridge_matching.dataset.ColoredMNIST
        root: datasets/colored_mnist
        train: true
        download: true
  test:
    batch_size: ${batch_size}
    num_workers: 5
    datasets:
      - _target_: bridge_matching.dataset.ColoredMNIST
        root: datasets/colored_mnist
        train: false
        download: true

metrics:
  - _target_: bridge_matching.metric.FIDMetric
    name: FID
    ref_path: stats/colored_mnist
    num_expected: 320
    batch_size: ${batch_size}

optimizer:
  _target_: torch.optim.Adam
  lr: 1e-3

lr_scheduler:
  _target_: torch.optim.lr_scheduler.ExponentialLR
  gamma: 0.9999995

trainer:
  log_step: 200
  len_epoch: 3000
  epochs: 30
  grad_norm_clip: 100
  images_dir: predicted_images
